[package]
name = "rsxtk"
version = "0.1.7"
authors = ["jrmarcum"]
edition = "2021"
description = "A standard-compliant Cargo Script manager for high-performance execution and WASM builds."
repository = "https://github.com/jrmarcum/rsx"
license = "MIT OR Apache-2.0"

[dependencies]
# CLI Parsing
clap = { version = "4.4", features = ["derive"] }
# TOML Manipulation
toml_edit = { version = "0.22", features = ["serde"] }
# Async and API
tokio = { version = "1.35", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"
# Utilities
anyhow = "1.0"
update-informer = "1.1"