[package]
name = "rsxtk"
version = "0.5.0"
authors = ["jrmarcum"]
edition = "2021"
description = "A standard-compliant Cargo Script manager for high-performance execution and WASM builds."
repository = "https://github.com/jrmarcum/rsx"
license = "MIT OR Apache-2.0"

[dependencies]
# Utilities
anyhow = "1.0"
# CLI Parsing
clap = { version = "4.4", features = ["derive"] }
# TOML Manipulation
toml_edit = { version = "0.23.9", features = ["serde"] }
# Async and API
tokio = { version = "1.35", features = ["full"] }
reqwest = { version = "0.13.1", features = ["json"] }
serde_json = "1.0"
update-informer = "1.1"
# Wasmtime integration
wasmtime = "40.0.1"
wasmtime-wasi = "40.0.1"
# wasm conversion features
wat = "1.21"
wasmprinter = "0.244.0"